/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Driver4Admin;

import Data.Admin;
import Data.Check;
import Database.ConnectionBuilder;
import Driver.LoginPage;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Witchapon Kaptop
 */
public class AdminMenu extends javax.swing.JFrame {
        
    /**
     * Creates new form AdminMenu
     */
    public AdminMenu() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ClearButton = new javax.swing.JButton();
        SubmitButton = new javax.swing.JButton();
        FirstNameText = new javax.swing.JTextField();
        LastNameText = new javax.swing.JTextField();
        PhoneText = new javax.swing.JTextField();
        EmailText = new javax.swing.JTextField();
        PasswordText = new javax.swing.JPasswordField();
        AdminBackButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        AdminIdLabel = new javax.swing.JLabel();
        AdminIdText = new javax.swing.JTextField();
        AdminFirstNameLabel = new javax.swing.JLabel();
        AdminFirstName = new javax.swing.JTextField();
        AdminLastNameLabel = new javax.swing.JLabel();
        AdminLastName = new javax.swing.JTextField();
        AdminPhoneLabel = new javax.swing.JLabel();
        AdminPhone = new javax.swing.JTextField();
        AdminEmailLabel = new javax.swing.JLabel();
        AdminEmail = new javax.swing.JTextField();
        SearchEditButton = new javax.swing.JButton();
        PasswordLabel = new javax.swing.JLabel();
        AdminPassword = new javax.swing.JTextField();
        EditButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        AdmninBackButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AdminId2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        AdminPassword2 = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        AdminDelete = new javax.swing.JTextField();
        DeleteButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        AdminBackButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AdminMenu");

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel3.setText("Last Name :  ");

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel4.setText("First Name :");

        jLabel5.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel5.setText("Phone :");

        jLabel6.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel6.setText("E-mail :");

        jLabel7.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel7.setText("Password :");

        ClearButton.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        ClearButton.setText("Clear");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        SubmitButton.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        FirstNameText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        LastNameText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        PhoneText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        EmailText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        PasswordText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PasswordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTextActionPerformed(evt);
            }
        });

        AdminBackButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        AdminBackButton1.setText("Back");
        AdminBackButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminBackButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FirstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhoneText, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailText, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(105, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AdminBackButton1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(AdminBackButton1)
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(FirstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(LastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(PhoneText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(EmailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add", jPanel2);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdminIdLabel.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        AdminIdLabel.setText("Admin Id :");
        jPanel1.add(AdminIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        AdminIdText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(AdminIdText, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 71, 303, -1));

        AdminFirstNameLabel.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        AdminFirstNameLabel.setText("First Name :");
        jPanel1.add(AdminFirstNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 104, 43));

        AdminFirstName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(AdminFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 303, -1));

        AdminLastNameLabel.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        AdminLastNameLabel.setText("Last Name :");
        jPanel1.add(AdminLastNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, 25));

        AdminLastName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(AdminLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 303, -1));

        AdminPhoneLabel.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        AdminPhoneLabel.setText("Phone :");
        jPanel1.add(AdminPhoneLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        AdminPhone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(AdminPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 303, -1));

        AdminEmailLabel.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        AdminEmailLabel.setText("E-mail :");
        jPanel1.add(AdminEmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));

        AdminEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(AdminEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 303, -1));

        SearchEditButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        SearchEditButton.setText("Search");
        SearchEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchEditButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SearchEditButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, -1, 28));

        PasswordLabel.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        PasswordLabel.setText("Password :");
        jPanel1.add(PasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 96, -1));

        AdminPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(AdminPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 303, -1));

        EditButton.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        EditButton.setText("Edit");
        EditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonActionPerformed(evt);
            }
        });
        jPanel1.add(EditButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 130, 55));

        jButton2.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 130, 55));

        AdmninBackButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        AdmninBackButton2.setText("Back");
        AdmninBackButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdmninBackButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(AdmninBackButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, -1, -1));

        jTabbedPane1.addTab("Edit", jPanel1);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel1.setText("Admin Id :");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 100, 20));

        AdminId2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel3.add(AdminId2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 149, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel2.setText("Admin Password :");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 150, 20));

        AdminPassword2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel3.add(AdminPassword2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 180, -1));

        jLabel8.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel8.setText("Admin Id To Delete :");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        AdminDelete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(AdminDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 272, 31));

        DeleteButton.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });
        jPanel3.add(DeleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 323, 130, 55));

        jButton3.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 323, 130, 55));

        AdminBackButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        AdminBackButton3.setText("Back");
        AdminBackButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminBackButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(AdminBackButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 0, -1, -1));

        jTabbedPane1.addTab("Delete", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        String value1 = FirstNameText.getText();
        String value2 = LastNameText.getText();
        String value3 = PhoneText.getText();
        String value4 = EmailText.getText();
        String value5 = PasswordText.getText();
        
        Check.checkTextAdmin(value1, value2, value3, value4, value5);
        Check.checkName("Admin", value1, value2);
        
        if(Check.getX()==1&Check.getY()==1){   
            try{
            Connection conn = ConnectionBuilder.getConnection();
            String sqlcmd ="INSERT INTO Admin_Data(Admin_Name ,Admin_Surname ,"
                    + "Admin_Phone , Admin_Email ,Admin_Password) values(?,?,?,?,?)";
            PreparedStatement pstm = conn.prepareStatement(sqlcmd);
            pstm.setString(1,value1);
            pstm.setString(2,value2);
            pstm.setString(3,value3);
            pstm.setString(4,value4);
            pstm.setString(5,value5);

            if(pstm.executeUpdate()>0){   
                JOptionPane.showMessageDialog(null,"Complete");
                conn.close(); 
                
            }
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(null,"Can't Add", "Warning",JOptionPane.ERROR_MESSAGE);
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null,"Error","Warning",JOptionPane.ERROR_MESSAGE);
            }
        }  
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        FirstNameText.setText("");
        LastNameText.setText("");
        PhoneText.setText("");
        EmailText.setText("");
        PasswordText.setText("");
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        String value1 = AdminId2.getText();
        String value2 = AdminDelete.getText();
        String password = AdminPassword2.getText();
        
        Check.checkDelete(value1,value2);
        
        if(Check.getX()==1){    
            try {
                int id = Integer.parseInt(AdminId2.getText());
                if(id==LoginPage.getUserId()&password.equals(LoginPage.getUserPassword())){
                    int adDelete = Integer.parseInt(AdminDelete.getText());
                    Connection conn = ConnectionBuilder.getConnection();
                    String sql = "DELETE FROM ADMIN_DATA WHERE admin_id=?";
                    PreparedStatement pstm = conn.prepareStatement(sql);
                    pstm.setInt(1,adDelete);
                    if(pstm.executeUpdate()>0){   
                        JOptionPane.showMessageDialog(null,"Delete Complete");
                        conn.close(); 
                    }
                }else{
                    JOptionPane.showMessageDialog(null,"ID or Password not correct", "Warning",JOptionPane.ERROR_MESSAGE);
                }
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(null,"Can't found delete ID.", "Warning",JOptionPane.ERROR_MESSAGE);
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null,"Please Enter character", "Warning",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void SearchEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchEditButtonActionPerformed
        try {
            int admin_id = Integer.parseInt(AdminIdText.getText());
            Connection conn = ConnectionBuilder.getConnection();
            String sql = "SELECT * FROM ADMIN_DATA WHERE ADMIN_id=?";
            PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.setInt(1, admin_id);
            ResultSet rs = pstm.executeQuery();
                                
            if (rs.next()) {
                AdminFirstName.setText(rs.getString("admin_name"));
                AdminLastName.setText(rs.getString("admin_surname"));
                AdminPhone.setText(rs.getString("admin_phone"));
                AdminEmail.setText(rs.getString("admin_email"));
                AdminPassword.setText(rs.getString("admin_password"));
            }else{
                AdminFirstName.setText("-");
                AdminLastName.setText("-");
                AdminPhone.setText("-");
                AdminEmail.setText("-");
                AdminPassword.setText("-");
                JOptionPane.showMessageDialog(null,"Cannot Found ID", "Warning",JOptionPane.ERROR_MESSAGE);
            }
            conn.close();  
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Error.", "Warning",JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null,"Please enter ID number.", "Warning",JOptionPane.ERROR_MESSAGE);
        }       
    }//GEN-LAST:event_SearchEditButtonActionPerformed

    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformed
        String value1 = AdminFirstName.getText();
        String value2 = AdminLastName.getText();
        String value3 = AdminPhone.getText();
        String value4 = AdminEmail.getText();
        String value5 = AdminPassword.getText();

        Check.checkTextAdmin(value1, value2, value3, value4, value5);
        Check.checkName("Admin", value1, value2);
        
        if(Check.getX()==1&Check.getY()==1){
            try {
                int admin_id = Integer.parseInt(AdminIdText.getText());
                Connection conn = ConnectionBuilder.getConnection();
                String sql = "UPDATE ADMIN_DATA SET admin_name=?,admin_surname=?,admin_phone=?"
                        + ",admin_email=?,admin_password=? WHERE admin_id=?";
                PreparedStatement pstm = conn.prepareStatement(sql);
                pstm.setString(1,value1);
                pstm.setString(2,value2);
                pstm.setString(3,value3);
                pstm.setString(4,value4);
                pstm.setString(5,value5);
                pstm.setInt(6,admin_id);
                if (pstm.executeUpdate() > 0) {
                    JOptionPane.showMessageDialog(null,"Edit Successfull.");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"Can't found ID", "Warning",JOptionPane.ERROR_MESSAGE);
            } catch (Exception ex){
                JOptionPane.showMessageDialog(null,"Please enter ID number.", "Warning",JOptionPane.ERROR_MESSAGE);
            }
        }    
    }//GEN-LAST:event_EditButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        AdminIdText.setText("");
        AdminFirstName.setText("");
        AdminLastName.setText("");
        AdminPhone.setText("");
        AdminEmail.setText("");        
        AdminPassword.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        AdminId2.setText("");
        AdminPassword2.setText("");
        AdminDelete.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void AdminBackButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminBackButton3ActionPerformed
        // TODO add your handling code here:
        AdminHome am = new AdminHome();
        this.setVisible(false);
        am.setVisible(true);
    }//GEN-LAST:event_AdminBackButton3ActionPerformed

    private void AdminBackButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminBackButton1ActionPerformed
        // TODO add your handling code here:
        AdminHome am = new AdminHome();
        this.setVisible(false);
        am.setVisible(true);
    }//GEN-LAST:event_AdminBackButton1ActionPerformed

    private void AdmninBackButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdmninBackButton2ActionPerformed
        // TODO add your handling code here:
        AdminHome am = new AdminHome();
        this.setVisible(false);
        am.setVisible(true);
    }//GEN-LAST:event_AdmninBackButton2ActionPerformed

    private void PasswordTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMenu().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminBackButton1;
    private javax.swing.JButton AdminBackButton3;
    private javax.swing.JTextField AdminDelete;
    private javax.swing.JTextField AdminEmail;
    private javax.swing.JLabel AdminEmailLabel;
    private javax.swing.JTextField AdminFirstName;
    private javax.swing.JLabel AdminFirstNameLabel;
    private javax.swing.JTextField AdminId2;
    private javax.swing.JLabel AdminIdLabel;
    private javax.swing.JTextField AdminIdText;
    private javax.swing.JTextField AdminLastName;
    private javax.swing.JLabel AdminLastNameLabel;
    private javax.swing.JTextField AdminPassword;
    private javax.swing.JPasswordField AdminPassword2;
    private javax.swing.JTextField AdminPhone;
    private javax.swing.JLabel AdminPhoneLabel;
    private javax.swing.JButton AdmninBackButton2;
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton EditButton;
    private javax.swing.JTextField EmailText;
    private javax.swing.JTextField FirstNameText;
    private javax.swing.JTextField LastNameText;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JPasswordField PasswordText;
    private javax.swing.JTextField PhoneText;
    private javax.swing.JButton SearchEditButton;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
