/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Driver4Admin;

import Data.Check;
import Database.ConnectionBuilder;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author First
 */
public class Register extends javax.swing.JFrame {
    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        CourseId.setEditable(false);
        RegisterNumber.setEditable(false);
        TutorId.setEditable(false);
        ReadRegisterId();
        ReadCourseName();
        ReadTutorName();       
        TextBoxTotal.setEditable(false);   
        PriceStudent.setEditable(false);
        ShowNameTextBox.setEditable(false);
        CourseId3.setEditable(false);
        Topic3.setEditable(false);
        ReadCourseId();
        TextBoxRegisterId.setEditable(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        jTextField1 = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        CourseStart = new javax.swing.JTextField();
        StudentMax = new javax.swing.JTextField();
        PriceCourse = new javax.swing.JTextField();
        TutorId = new javax.swing.JTextField();
        CourseEnd = new javax.swing.JTextField();
        CourseTime = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        CourseId = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        RegisterNumber = new javax.swing.JTextField();
        NameBox = new javax.swing.JComboBox<>();
        TurtorBox = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ConfirmButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        StudentId = new javax.swing.JTextField();
        PriceStudent = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Coupon = new javax.swing.JTextField();
        CheckCoupon = new javax.swing.JButton();
        TextBoxRegisterId = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        TextBoxTotal = new javax.swing.JTextField();
        ShowNameTextBox = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        CourseIdbox = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        Register3 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        CourseId3 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        Topic3 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        CourseOpen1 = new javax.swing.JRadioButton();
        CourseEnd1 = new javax.swing.JRadioButton();
        ConfirmButton2 = new javax.swing.JButton();
        Clear2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register");

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CourseStart.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CourseStart.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CourseStart.setText("dd/mm/yyyy");
        CourseStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CourseStartActionPerformed(evt);
            }
        });
        jPanel1.add(CourseStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 170, -1));

        StudentMax.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(StudentMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 170, -1));

        PriceCourse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(PriceCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 160, -1));

        TutorId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TutorId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TutorIdActionPerformed(evt);
            }
        });
        jPanel1.add(TutorId, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 161, -1));

        CourseEnd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CourseEnd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CourseEnd.setText("dd/mm/yyyy");
        CourseEnd.setToolTipText("");
        jPanel1.add(CourseEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 161, -1));

        CourseTime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(CourseTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 170, -1));

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel1.setText("Course ID :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel2.setText("Course Start :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel3.setText("Student Max :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel4.setText("Price :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel5.setText("Tutor ID :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel6.setText("Course End :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        jLabel7.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel7.setText("Course Time :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jButton1.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        jButton2.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, 100, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, -1, -1));

        jLabel11.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel11.setText("Course Name :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 20));

        CourseId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CourseId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CourseIdActionPerformed(evt);
            }
        });
        jPanel1.add(CourseId, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 170, -1));

        jLabel12.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel12.setText("Tutor Name : ");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, -1));

        jLabel13.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel13.setText("Register Number :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 20));

        RegisterNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RegisterNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterNumberActionPerformed(evt);
            }
        });
        jPanel1.add(RegisterNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 180, -1));

        NameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameBoxActionPerformed(evt);
            }
        });
        jPanel1.add(NameBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 170, -1));

        TurtorBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TurtorBoxActionPerformed(evt);
            }
        });
        jPanel1.add(TurtorBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 160, -1));

        jTabbedPane1.addTab("Course", jPanel1);

        jPanel2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel2FocusGained(evt);
            }
        });
        jPanel2.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jPanel2InputMethodTextChanged(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel8.setText("Register ID :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 72, -1, -1));

        jLabel9.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel9.setText("Student Name :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, -1));

        ConfirmButton.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        ConfirmButton.setText("Confirm");
        ConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmButtonActionPerformed(evt);
            }
        });
        jPanel2.add(ConfirmButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        ClearButton.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        ClearButton.setText("Clear");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });
        jPanel2.add(ClearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 91, -1));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton7.setText("Back");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, -1, -1));

        StudentId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        StudentId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentIdActionPerformed(evt);
            }
        });
        jPanel2.add(StudentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 166, -1));

        PriceStudent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PriceStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriceStudentActionPerformed(evt);
            }
        });
        jPanel2.add(PriceStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 166, -1));

        jLabel10.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel10.setText("Price :");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLabel15.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel15.setText("Coupon :");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, -1, 20));

        Coupon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Coupon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CouponActionPerformed(evt);
            }
        });
        jPanel2.add(Coupon, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 165, -1));

        CheckCoupon.setText("Check");
        CheckCoupon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckCouponActionPerformed(evt);
            }
        });
        jPanel2.add(CheckCoupon, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, -1, -1));

        TextBoxRegisterId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TextBoxRegisterId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextBoxRegisterIdActionPerformed(evt);
            }
        });
        jPanel2.add(TextBoxRegisterId, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 76, 167, -1));

        jLabel14.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel14.setText("Total :");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        TextBoxTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TextBoxTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextBoxTotalActionPerformed(evt);
            }
        });
        jPanel2.add(TextBoxTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 165, -1));

        ShowNameTextBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ShowNameTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowNameTextBoxActionPerformed(evt);
            }
        });
        jPanel2.add(ShowNameTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 166, -1));

        jLabel16.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel16.setText("Student ID :");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel17.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel17.setText("Course ID :");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 23, -1, -1));

        CourseIdbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CourseIdbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CourseIdboxActionPerformed(evt);
            }
        });
        jPanel2.add(CourseIdbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 30, 166, -1));

        jTabbedPane1.addTab("Student", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Register3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Register3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Register3ActionPerformed(evt);
            }
        });
        jPanel3.add(Register3, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 47, 152, -1));

        jLabel18.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel18.setText("Register ID :");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, 20));

        CourseId3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(CourseId3, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 89, 152, -1));

        jLabel19.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel19.setText("Course ID :");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 88, 100, -1));

        Topic3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(Topic3, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 131, 152, -1));

        jLabel20.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel20.setText("Topic :");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 130, -1, -1));

        CourseOpen1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CourseOpen1.setText("Course Open");
        CourseOpen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CourseOpen1ActionPerformed(evt);
            }
        });
        jPanel3.add(CourseOpen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 172, -1, -1));

        CourseEnd1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CourseEnd1.setText("Course End");
        CourseEnd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CourseEnd1ActionPerformed(evt);
            }
        });
        jPanel3.add(CourseEnd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 209, -1, -1));

        ConfirmButton2.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        ConfirmButton2.setText("Confirm");
        ConfirmButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(ConfirmButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 130, 55));

        Clear2.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        Clear2.setText("Clear");
        Clear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clear2ActionPerformed(evt);
            }
        });
        jPanel3.add(Clear2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, 130, 55));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton6.setText("Back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, -1, -1));

        jTabbedPane1.addTab("Course End", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CourseStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CourseStartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CourseStartActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        AdminHome ah = new AdminHome();
        ah.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void ConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmButtonActionPerformed
        try{
            int rgId = Integer.parseInt(TextBoxRegisterId.getText());
            int stdId = Integer.parseInt(StudentId.getText());
            double price = Double.parseDouble(PriceStudent.getText());
            Connection conn = ConnectionBuilder.getConnection();
            String sql = "Select Student_max, Student_Count FROM Register"
                    + " WHERE Register_Id = ?";
            
            PreparedStatement pstm =conn.prepareStatement(sql);
            pstm.setInt(1,rgId);
            ResultSet rs = pstm.executeQuery();
            if(rs.next()){
                if(rs.getInt("Student_max")>rs.getInt("Student_Count")){
                    Check.checkRgdetail(stdId,rgId);
                    if(Check.getY()==1){
                        String sql2 ="INSERT INTO registerdetail(register_id ,student_id ,Student_price)"
                                   + " values(?,?,?)";
                        PreparedStatement pstm2 = conn.prepareStatement(sql2);
                        pstm2.setInt(1,rgId);
                        pstm2.setInt(2,stdId);
                        pstm2.setDouble(3,price);

                        String sql3 ="Update Register SET Student_Count = ? WHERE Register_Id =?";
                        PreparedStatement pstm3 = conn.prepareStatement(sql3);
                        pstm3.setInt(1,rs.getInt("Student_Count")+1);
                        pstm3.setInt(2,rgId);

                        if(pstm2.executeUpdate()>0&pstm3.executeUpdate()>0){
                            refresh();
                            JOptionPane.showMessageDialog(null,"Complete");
                            conn.close();                        
                        }
                    }  
                }else {
                    JOptionPane.showMessageDialog(null,"Course is full now.", "Warning",JOptionPane.ERROR_MESSAGE);
                }
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"Can't found ID", "Warning",JOptionPane.ERROR_MESSAGE);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Please enter number","Warning",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ConfirmButtonActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        AdminHome ah = new AdminHome();
        ah.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String value1 = TutorId.getText();
        String value2 = CourseId.getText();
        String value3 = CourseStart.getText();
        String value4 = CourseEnd.getText();
        String value5 = StudentMax.getText();
        String value6 = CourseTime.getText();
        String value7 = PriceCourse.getText();
        
        Check.rgCourse(value1, value2, value3, value4, value5, value6, value7);
        Check.checkRgCourseId(value2);
        int tutorId = Integer.parseInt(value1);
        int stMax = Integer.parseInt(value5);
        double price = Double.parseDouble(value7);
        
        if(Check.getX()==1&Check.getY()==1){   
            try{
            Connection conn = ConnectionBuilder.getConnection();
            String sqlcmd ="INSERT INTO register(TUTOR_ID ,Course_ID,"
                    + "DATE_START , DATE_END, STUDENT_MAX, COURSE_TIME,Student_Count, COURSE_PRICE,Course_Open)"
                    + " values(?,?,?,?,?,?,?,?,?)";
            PreparedStatement pstm = conn.prepareStatement(sqlcmd);
            pstm.setInt(1,tutorId);
            pstm.setString(2,value2);
            pstm.setString(3,value3);
            pstm.setString(4,value4);
            pstm.setInt(5,stMax);
            pstm.setString(6,value6);
            pstm.setInt(7, 0);
            pstm.setDouble(8,price);
            pstm.setBoolean(9,true);
            if(pstm.executeUpdate()>0){   
                refresh();
                JOptionPane.showMessageDialog(null,"Complete");
                conn.close(); 
                
            }
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(null,"Can't found ID", "Warning",JOptionPane.ERROR_MESSAGE);
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null,"Error","Warning",JOptionPane.ERROR_MESSAGE);
            }
        }  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
       TextBoxRegisterId.setText("");
       StudentId.setText("");
       Coupon.setText("");
       PriceStudent.setText("");
       TextBoxTotal.setText("");
       ShowNameTextBox.setText("");
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       TutorId.setText("");
       CourseId.setText("");
       CourseStart.setText("dd/mm/yyyy");
       CourseEnd.setText("dd/mm/yyyy");
       StudentMax.setText("");
       CourseTime.setText("");
       PriceCourse.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void NameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameBoxActionPerformed
        try{
            String courseName = (String)NameBox.getSelectedItem();
            Connection conn = ConnectionBuilder.getConnection();
            String sql ="SELECT Course_Id FROM Course WHERE Course_Name = ? ";
            PreparedStatement pstm =conn.prepareStatement(sql);
            pstm.setString(1, courseName);
            ResultSet rs = pstm.executeQuery();
            if(rs.next()){
              CourseId.setText(rs.getString("Course_Id"));
              
            }
            conn.close();
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"Error Conn Course Table.", "Warning",JOptionPane.ERROR_MESSAGE);
        }
       
    }//GEN-LAST:event_NameBoxActionPerformed

    private void RegisterNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterNumberActionPerformed

    private void StudentIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentIdActionPerformed
        // TODO add your handling code here:
        try{
            int studentId = Integer.parseInt(StudentId.getText());
            Connection conn = ConnectionBuilder.getConnection();
            String sql = "SELECT Student_Name ,Student_Surname FROM Student_Data WHERE Student_Id =? ";
            PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.setInt(1, studentId);
            ResultSet rs =pstm.executeQuery();
            if(rs.next()){
                ShowNameTextBox.setText(rs.getString("Student_Name")+" "+rs.getString("Student_Surname"));
            }else{
                JOptionPane.showMessageDialog(null,"Student Id is not exist.", "Warning", JOptionPane.ERROR_MESSAGE);
                ShowNameTextBox.setText("");
            }
        }catch(SQLException ex){
             JOptionPane.showMessageDialog(null,"Error Conn Student Table.", "Warning", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_StudentIdActionPerformed

    private void TurtorBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TurtorBoxActionPerformed
        try{
            if(TurtorBox.getSelectedItem()!=null){
                
        String[] result  =((String)TurtorBox.getSelectedItem()).split(" ");
        String tutorName = result[0];
        Connection conn = ConnectionBuilder.getConnection();
        String sql = "SELECT Tutor_Id FROM Tutor_Data WHERE Tutor_Name = ? ";
        PreparedStatement pstm = conn.prepareStatement(sql);
        pstm.setString(1, tutorName);
        ResultSet rs = pstm.executeQuery();
        if(rs.next()){
            TutorId.setText(rs.getString("Tutor_Id"));
        }
          conn.close();
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"Error Conn Tutor Table.", "Warning", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_TurtorBoxActionPerformed

    private void CourseIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CourseIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CourseIdActionPerformed

    private void TutorIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TutorIdActionPerformed
        
    }//GEN-LAST:event_TutorIdActionPerformed

    private void CouponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CouponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CouponActionPerformed

    private void CheckCouponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckCouponActionPerformed
        String coupon = Coupon.getText();
        try{
            Connection conn = ConnectionBuilder.getConnection();
            String sql ="SELECT Promotion_discount,Promotion_Isok FROM Promotion WHERE Promotion_code = ? ";
            PreparedStatement pstm =conn.prepareStatement(sql);
            pstm.setString(1, coupon);
            ResultSet rs = pstm.executeQuery();
            if(rs.next()){
                if(rs.getBoolean("Promotion_Isok")){
                    double total = Double.parseDouble(PriceStudent.getText())-rs.getDouble("Promotion_discount");
                    String sql2 ="UPDATE Promotion SET Promotion_isok=? WHERE Promotion_code = ? ";
                    PreparedStatement pstm2 =conn.prepareStatement(sql2);
                    pstm2.setBoolean(1,false);
                    pstm2.setString(2,coupon);
                    
                    if(pstm2.executeUpdate()>0){
                        TextBoxTotal.setText(total+"");
                        JOptionPane.showMessageDialog(null,"Your price is discount: "+rs.getDouble("Promotion_discount")+" Baht");
                    }
                    
                }else{
                    JOptionPane.showMessageDialog(null,"This Coupon is Expire", "Warning",JOptionPane.ERROR_MESSAGE);
                    Coupon.setText("");
                    conn.close();
                }
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"Can't found this coupon.", "Warning",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_CheckCouponActionPerformed

    private void PriceStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriceStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PriceStudentActionPerformed

    private void TextBoxRegisterIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextBoxRegisterIdActionPerformed
                
    }//GEN-LAST:event_TextBoxRegisterIdActionPerformed

    private void TextBoxTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextBoxTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextBoxTotalActionPerformed

    private void ShowNameTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowNameTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ShowNameTextBoxActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        AdminHome ah = new AdminHome();
        ah.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void Register3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Register3ActionPerformed
        try{
          int registerId =Integer.parseInt(Register3.getText()) ;
            
            Connection conn = ConnectionBuilder.getConnection();
            String sql ="SELECT r.Course_Id,r.Course_Open,c.Course_Topic "
                    + "FROM Register r "
                    + "INNER JOIN Course c "
                    + "ON r.course_Id = c.course_ID WHERE r.Register_Id =?";
            PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.setInt(1, registerId);
            ResultSet rs =pstm.executeQuery();
            if(rs.next()){               
                CourseId3.setText(rs.getString("Course_Id"));
                Topic3.setText(rs.getString("Course_Topic"));
                if(rs.getBoolean("Course_Open")){
                    CourseOpen1.setSelected(true);
                }else{
                    CourseEnd1.setSelected(true);
                }               
            }else{
                JOptionPane.showMessageDialog(null,"Can't found this RegisterId.", "Warning",JOptionPane.ERROR_MESSAGE);
                 PriceStudent.setText("");
            }
                                                          
        }catch(SQLException ex){
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Register3ActionPerformed

    private void CourseOpen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CourseOpen1ActionPerformed
        if(CourseOpen1.isSelected())
            CourseEnd1.setSelected(false);
    }//GEN-LAST:event_CourseOpen1ActionPerformed

    private void CourseEnd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CourseEnd1ActionPerformed
        if(CourseEnd1.isSelected())
            CourseOpen1.setSelected(false);
    }//GEN-LAST:event_CourseEnd1ActionPerformed

    private void ConfirmButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmButton2ActionPerformed
        boolean courseStatus = true;
        if(CourseEnd1.isSelected()){
            courseStatus = false;
        }
        try {
            int register_id = Integer.parseInt(Register3.getText());
            Connection conn = ConnectionBuilder.getConnection();
            String sql = "UPDATE Register SET course_open=? WHERE register_id=?";
            PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.setBoolean(1,courseStatus);
            pstm.setInt(2,register_id);
            
            if (pstm.executeUpdate() > 0) {           
                refresh();
                CourseIdbox.setSelectedIndex(0);
                JOptionPane.showMessageDialog(null,"Successfull.");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Can't Edit", "Warning",JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null,"Please enter ID number.", "Warning",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ConfirmButton2ActionPerformed

    private void Clear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clear2ActionPerformed
        CourseId3.setText("");
        Topic3.setText("");
        CourseOpen1.setSelected(false);
        CourseEnd1.setSelected(false);
    }//GEN-LAST:event_Clear2ActionPerformed

    private void CourseIdboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CourseIdboxActionPerformed
        String courseId = (String)CourseIdbox.getSelectedItem();
        try {            
            Connection conn = ConnectionBuilder.getConnection();
            String sql ="SELECT Register_Id,Course_Open,Course_Price FROM Register "
                    + "WHERE Course_Id LIKE ? ";
            PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.setString(1, courseId);
            ResultSet rs =pstm.executeQuery();
            if(rs.next()){
                TextBoxRegisterId.setText(rs.getString("Register_id"));
                PriceStudent.setText(""+rs.getDouble("Course_Price"));
                TextBoxTotal.setText(""+rs.getDouble("Course_Price"));
                
            }
      
        } catch (SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CourseIdboxActionPerformed

    private void jPanel2InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jPanel2InputMethodTextChanged

    }//GEN-LAST:event_jPanel2InputMethodTextChanged

    private void jPanel2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel2FocusGained

    }//GEN-LAST:event_jPanel2FocusGained

    private void ReadRegisterId() {
        try{
        Connection conn = ConnectionBuilder.getConnection();
        String sql = "SELECT Register_Id FROM Register ORDER BY Register_Id DESC";
        PreparedStatement pstm = conn.prepareStatement(sql) ;
        ResultSet rs = pstm.executeQuery();           
         
        if (rs.next()) {
            int aa= rs.getInt("Register_Id")+1;
            RegisterNumber.setText(Integer.toString(aa));
        }else{
            RegisterNumber.setText("1");
        }
          conn.close();
        }catch(SQLException ex){
             JOptionPane.showMessageDialog(null,"Error Register con table.", "Warning",JOptionPane.ERROR_MESSAGE);
      
        }
    }
    private void ReadCourseName(){
        try{
            Connection conn = ConnectionBuilder.getConnection();
            String sql ="SELECT Course_Name FROM Course ";                
            PreparedStatement pstm =conn.prepareStatement(sql);
            ResultSet rs =pstm.executeQuery();
            NameBox.removeAllItems();
            NameBox.addItem("--Select Course--");
            while(rs.next()){
                NameBox.addItem(rs.getString("Course_Name"));
            }     
            conn.close();
        }catch(SQLException ex){
             JOptionPane.showMessageDialog(null,"Error Conn Course Table.", "Warning",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void ReadTutorName(){   
        try{
            Connection conn = ConnectionBuilder.getConnection();
            String sql = "SELECT Tutor_Name ,Tutor_surname FROM Tutor_Data ";
            PreparedStatement pstm = conn.prepareStatement(sql);
            ResultSet rs = pstm.executeQuery();
            TurtorBox.removeAllItems();
            TurtorBox.addItem("--Select TutorName--");
            while(rs.next()){
                TurtorBox.addItem(rs.getString("Tutor_Name")+" "+rs.getString("tutor_surname"));
            }
            conn.close();
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"Error Conn Tutor table.", "Warning",JOptionPane.ERROR_MESSAGE);
        }        
    }
    
    private void ReadCourseId(){
        try{
            Connection conn = ConnectionBuilder.getConnection();
            String sql ="SELECT Course_ID FROM Register Where Course_Open = true";
            Statement st =conn.createStatement();
            ResultSet rs =st.executeQuery(sql);
            CourseIdbox.removeAllItems();
            CourseIdbox.addItem("--Select Course--");
            
            while(rs.next()){
                CourseIdbox.addItem(rs.getString("Course_ID"));
            }
        }catch(SQLException ex){
             JOptionPane.showMessageDialog(null,"Error Conn Course Table.", "Warning",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void refresh(){
        TutorId.setText("");
        CourseId.setText("");
        CourseStart.setText("dd/mm/yyyy");
        CourseEnd.setText("dd/mm/yyyy");
        StudentMax.setText("");
        CourseTime.setText("");
        PriceCourse.setText("");
        CourseId.setEditable(false);
        RegisterNumber.setEditable(false);
        TutorId.setEditable(false);
        ReadRegisterId();
        ReadCourseName();
        ReadTutorName();
        ReadCourseId();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckCoupon;
    private javax.swing.JButton Clear2;
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton ConfirmButton;
    private javax.swing.JButton ConfirmButton2;
    private javax.swing.JTextField Coupon;
    private javax.swing.JTextField CourseEnd;
    private javax.swing.JRadioButton CourseEnd1;
    private javax.swing.JTextField CourseId;
    private javax.swing.JTextField CourseId3;
    private javax.swing.JComboBox<String> CourseIdbox;
    private javax.swing.JRadioButton CourseOpen1;
    private javax.swing.JTextField CourseStart;
    private javax.swing.JTextField CourseTime;
    private javax.swing.JComboBox<String> NameBox;
    private javax.swing.JTextField PriceCourse;
    private javax.swing.JTextField PriceStudent;
    private javax.swing.JTextField Register3;
    private javax.swing.JTextField RegisterNumber;
    private javax.swing.JTextField ShowNameTextBox;
    private javax.swing.JTextField StudentId;
    private javax.swing.JTextField StudentMax;
    private javax.swing.JTextField TextBoxRegisterId;
    private javax.swing.JTextField TextBoxTotal;
    private javax.swing.JTextField Topic3;
    private javax.swing.JComboBox<String> TurtorBox;
    private javax.swing.JTextField TutorId;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    
}
