/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Driver4Admin;

import Driver4Admin.AdminHome;
import Data.Check;
import Data.Student;
import Database.ConnectionBuilder;
import Driver.LoginPage;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Witchapon-Pc
 */
public class StudentMenu extends javax.swing.JFrame {

    /**
     * Creates new form StudentMenu
     */
    public StudentMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        FirstNameText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        LastNameText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        EmailText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        PhoneText = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        StudentIdText = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        StudentFirstName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        StudentLastName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        StudentPhone = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        StudentEmail = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        AdminId2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        StudentDelete = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("StudentMenu");

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel1.setText("First Name :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        FirstNameText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(FirstNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 330, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel2.setText("Last Name :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 100, -1));

        LastNameText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(LastNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 330, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel3.setText("E-mail :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        EmailText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(EmailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 330, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel4.setText("Phone :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        PhoneText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(PhoneText, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 330, -1));

        jButton2.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 130, 55));

        jButton3.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 130, 55));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, -1, -1));

        jTabbedPane1.addTab("Add", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel5.setText("Student ID :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 72, -1, 20));

        StudentIdText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(StudentIdText, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 260, -1));

        jButton5.setText("Search");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel6.setText("First Name :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 125, -1, -1));

        StudentFirstName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(StudentFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 126, 212, -1));

        jLabel7.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel7.setText("Last Name :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 125, -1, -1));

        StudentLastName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(StudentLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 180, -1));

        jLabel8.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel8.setText("Phone :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 70, 20));

        StudentPhone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(StudentPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 212, -1));

        jLabel9.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel9.setText("E-mail :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 70, 20));

        StudentEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(StudentEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 180, -1));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton6.setText("Back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 0, -1, -1));

        jButton7.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jButton7.setText("Edit");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 130, 55));

        jButton8.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jButton8.setText("Clear");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 130, 55));

        jTabbedPane1.addTab("Edit", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel10.setText("Admin ID :");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 80, -1, -1));

        AdminId2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(AdminId2, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 84, 170, -1));

        jLabel11.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel11.setText("Password :");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 80, -1, -1));

        jPasswordField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 84, 190, -1));

        jLabel12.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel12.setText("Student ID For Delete :");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 154, -1, -1));

        StudentDelete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(StudentDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 158, 255, -1));

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton9.setText("Back");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 0, -1, -1));

        jButton10.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jButton10.setText("Delete");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 130, 60));

        jButton11.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jButton11.setText("Clear");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 131, 56));

        jTabbedPane1.addTab("Delete", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String value1 = FirstNameText.getText();
        String value2 = LastNameText.getText();
        String value3 = PhoneText.getText();
        String value4 = EmailText.getText();
        
        Check.checkTextStudent(value1, value2, value3, value4);
        Check.checkName("Student", value1, value2);
        
        if(Check.getX()==1&Check.getY()==1){
            try{
            Connection conn = ConnectionBuilder.getConnection();
            String sqlcmd ="INSERT INTO Student_Data(Student_Name ,Student_Surname ,"
                    + "Student_Phone , Student_Email) values(?,?,?,?)";
            PreparedStatement pstm = conn.prepareStatement(sqlcmd);
            pstm.setString(1,value1);
            pstm.setString(2,value2);
            pstm.setString(3,value3);
            pstm.setString(4,value4);

            if(pstm.executeUpdate()>0){   
                JOptionPane.showMessageDialog(null,"Complete");
                conn.close(); 
                
            }
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(null,"Can't Add", "Warning",JOptionPane.ERROR_MESSAGE);
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null,"Error","Warning",JOptionPane.ERROR_MESSAGE);
            }
        }  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        FirstNameText.setText("");
        LastNameText.setText("");
        PhoneText.setText("");
        EmailText.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        AdminHome am = new AdminHome();
        this.setVisible(false);
        am.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        AdminHome am = new AdminHome();
        this.setVisible(false);
        am.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            int student_id = Integer.parseInt(StudentIdText.getText());
            Connection conn = ConnectionBuilder.getConnection();
            String sql = "SELECT * FROM Student_DATA WHERE Student_id=?";
            PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.setInt(1, student_id);
            ResultSet rs = pstm.executeQuery();
                                
            if (rs.next()) {
                StudentFirstName.setText(rs.getString("Student_name"));
                StudentLastName.setText(rs.getString("Student_surname"));
                StudentPhone.setText(rs.getString("Student_phone"));
                StudentEmail.setText(rs.getString("Student_email"));
            }else{
                StudentFirstName.setText("-");
                StudentLastName.setText("-");
                StudentPhone.setText("-");
                StudentEmail.setText("-");
                JOptionPane.showMessageDialog(null,"Cannot Found ID", "Warning",JOptionPane.ERROR_MESSAGE);
            }
            conn.close();  
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Error.", "Warning",JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null,"Please enter ID number.", "Warning",JOptionPane.ERROR_MESSAGE);
        }        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        AdminHome am = new AdminHome();
        this.setVisible(false);
        am.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        String value1 = AdminId2.getText();
        String value2 = StudentDelete.getText();
        Check.checkDelete(value1,value2);
        
        if(Check.getX()==1){
            try {
                int id = Integer.parseInt(AdminId2.getText());
                String password = jPasswordField2.getText();
                if(id==LoginPage.getUserId()&password.equals(LoginPage.getUserPassword())){
                    int stDelete = Integer.parseInt(StudentDelete.getText());
                    Connection conn = ConnectionBuilder.getConnection();
                    String sql = "DELETE FROM Student_DATA WHERE student_id=?";
                    PreparedStatement pstm = conn.prepareStatement(sql);
                    pstm.setInt(1,stDelete);
                    if(pstm.executeUpdate()>0){   
                        JOptionPane.showMessageDialog(null,"Delete Complete");
                        conn.close(); 
                    }
                }else{
                    JOptionPane.showMessageDialog(null,"ID or Password not correct", "Warning",JOptionPane.ERROR_MESSAGE);
                }
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(null,"Can't Delete", "Warning",JOptionPane.ERROR_MESSAGE);
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null,"Please Enter character", "Warning",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String value1 = StudentFirstName.getText();
        String value2 = StudentLastName.getText();
        String value3 = StudentPhone.getText();
        String value4 = StudentEmail.getText();

        Check.checkTextStudent(value1, value2, value3, value4);
        Check.checkName("Student", value1, value2);
        
        if(Check.getX()==1&Check.getY()==1){
            try {
                int student_id = Integer.parseInt(StudentIdText.getText());
                Connection conn = ConnectionBuilder.getConnection();
                String sql = "UPDATE Student_DATA SET student_name=?,student_surname=?,student_phone=?"
                        + ",student_email=? WHERE student_id=?";
                PreparedStatement pstm = conn.prepareStatement(sql);
                pstm.setString(1,value1);
                pstm.setString(2,value2);
                pstm.setString(3,value3);
                pstm.setString(4,value4);
                pstm.setInt(6,student_id);
                if (pstm.executeUpdate() > 0) {
                    JOptionPane.showMessageDialog(null,"Edit Successfull.");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"Can't Edit", "Warning",JOptionPane.ERROR_MESSAGE);
            } catch (Exception ex){
                JOptionPane.showMessageDialog(null,"Please enter ID number.", "Warning",JOptionPane.ERROR_MESSAGE);
            }
        }    
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        AdminId2.setText("");
        jPasswordField2.setText("");
        StudentDelete.setText("");
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        StudentIdText.setText("");
        StudentFirstName.setText("");
        StudentLastName.setText("");
        StudentPhone.setText("");
        StudentEmail.setText("");
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AdminId2;
    private javax.swing.JTextField EmailText;
    private javax.swing.JTextField FirstNameText;
    private javax.swing.JTextField LastNameText;
    private javax.swing.JTextField PhoneText;
    private javax.swing.JTextField StudentDelete;
    private javax.swing.JTextField StudentEmail;
    private javax.swing.JTextField StudentFirstName;
    private javax.swing.JTextField StudentIdText;
    private javax.swing.JTextField StudentLastName;
    private javax.swing.JTextField StudentPhone;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
