/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Driver;

import Driver4Admin.AdminHome;
import Database.ConnectionBuilder;
import Driver4Tutor.TutorHome;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Witchapon Kaptop
 */
public class LoginPage extends javax.swing.JFrame {
    private static int userId;
    private static String userPassword;

    public static int getUserId() {
        return userId;
    }
    
    public static String getUserPassword(){
        return userPassword;
    }
    
    public LoginPage() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userIdText = new javax.swing.JTextField();
        confirmButton = new javax.swing.JButton();
        userPasswordText = new javax.swing.JPasswordField();
        CloseButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SchoolSystem");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userIdText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        userIdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userIdTextActionPerformed(evt);
            }
        });
        getContentPane().add(userIdText, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 140, 20));

        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        getContentPane().add(confirmButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        userPasswordText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        userPasswordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userPasswordTextActionPerformed(evt);
            }
        });
        getContentPane().add(userPasswordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 140, 20));

        CloseButton.setText("Close");
        CloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CloseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 80, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Driver/Testlogin01.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userIdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userIdTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userIdTextActionPerformed
    /*
    เช็คดูว่าผู้ที่Log-inเข้ามานั้นเป็นAdmin หรือ Tutor โดบถ้าเป็นAdninจะให้เข้าหน้าAdminHome
    ถ้าเป็นTutor จะให้ไปเข้าTutor_Home โดยจะตรวจCheck Password เช็คว่ามีIdนี้อยู่หรือไม่เเละเช็คว่าที่กรอกมาใส่เป็นตัวเลขIdหรือไม่
    ถ้าไม่ให้Message Boxเตือน
    */
    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        ResultSet rsu = null;
        String password = null;
        String idType = null;
        try{
            int id = Integer.parseInt(userIdText.getText());
            if(id>=10000 && id<20000){
                idType = "Admin";
            }else if(id>=20000 && id<30000){
                idType = "Tutor";
            }
            Connection conn = ConnectionBuilder.getConnection();
            String sqlcmd = "select * From "+idType+"_Data where "+idType+"_Id=? ";
            PreparedStatement pstm =conn.prepareStatement(sqlcmd);
            pstm.setInt(1,id);
            rsu=pstm.executeQuery();
            rsu.next();
            password = rsu.getString(idType+"_password");
            if(password.equals(userPasswordText.getText())){
                if(idType.equals("Admin")){
                    userId = id;
                    userPassword = password;
                    AdminHome ma = new AdminHome();
                    ma.setVisible(true);
                    this.setVisible(false);
                    conn.close();
                }else if(idType.equals("Tutor")){
                    userId = id;
                    userPassword = password;
                    TutorHome th = new TutorHome();
                    th.setVisible(true);
                    this.setVisible(false);
                    conn.close();
                }
            }else{
                JOptionPane.showMessageDialog(null, "Your password is incorrect!", "Warning", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Cannot found ID", "Warning", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Please Enter Number of Id.", "Warning", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void userPasswordTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userPasswordTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userPasswordTextActionPerformed

    private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_CloseButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField userIdText;
    private javax.swing.JPasswordField userPasswordText;
    // End of variables declaration//GEN-END:variables
}
